name: CMake Build and Test

on:
  [push, pull_request]

jobs:
  Build Windows:
    name: Windows ${{ matrix.build_type }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          [Release, Debug]
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_CONFIGURATION_TYPES=${{ matrix.build_type }} -DSERIALIZE_BUILD_TESTING=ON -DSERIALIZE_BUILD_EXAMPLES=ON -DCMAKE_CXX_FLAGS="/Zc:__cplusplus /std:c++20 /utf-8"
      env:
        CC: cl
        CXX: cl

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -C ${{ matrix.build_type }} --output-on-failure

  Build Linux:
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    container: fedora:latest # Has updated GCC and CLang versions in comparison to ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          [Release, Debug]
        config:
        - name: "Linux GCC"
          cc: "gcc"
          cxx: "g++"
        - name: "Linux CLang"
          cc: "clang"
          cxx: "clang++"

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DSERIALIZE_BUILD_TESTING=ON -DSERIALIZE_BUILD_EXAMPLES=ON
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
